const Actions = {
    PRODUCT_LIST_REQUEST : 'PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_SUCCESS : 'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_FAILURE : 'PRODUCT_LIST_FAILURE',
    USER_EMAIL : 'USER_EMAIL',
    PRODUCT_ID : 'PRODUCT_ID',
    QUANTITY : 'QUANTITY',
    TAX_PER_ITEM : 'TAX_PER_ITEM',
    ITEM_PRICE : 'ITEM_PRICE',
    PRICE_PER_ITEM : 'PRICE_PER_ITEM', 
    NEW_TABLE_VALUES : 'NEW_TABLE_VALUES',
    TABLE_VALUES : 'TABLE_VALUES',
    DENOMINATION : 'DENOMINATION',
    CUSTOMER_AMOUNT : 'CUSTOMER_AMOUNT',
    CUSTOMER_FINAL_AMOUNT : 'CUSTOMER_FINAL_AMOUNT',
    REMAINING_AMOUNT : 'REMAINING_AMOUNT', 
    CUSTOMER_DENOMINATION : 'CUSTOMER_DENOMINATION',
}

export default Actions